package com.rda.example.spring.tx.model;

import java.util.Date;


public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.id
	 * @mbggenerated  Mon Sep 15 11:07:53 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.name
	 * @mbggenerated  Mon Sep 15 11:07:53 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.create_time
	 * @mbggenerated  Mon Sep 15 11:07:53 CST 2014
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.id
	 * @return  the value of t_role.id
	 * @mbggenerated  Mon Sep 15 11:07:53 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.id
	 * @param id  the value for t_role.id
	 * @mbggenerated  Mon Sep 15 11:07:53 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.name
	 * @return  the value of t_role.name
	 * @mbggenerated  Mon Sep 15 11:07:53 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.name
	 * @param name  the value for t_role.name
	 * @mbggenerated  Mon Sep 15 11:07:53 CST 2014
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.create_time
	 * @return  the value of t_role.create_time
	 * @mbggenerated  Mon Sep 15 11:07:53 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.create_time
	 * @param createTime  the value for t_role.create_time
	 * @mbggenerated  Mon Sep 15 11:07:53 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role
	 * @mbggenerated  Mon Sep 15 11:07:53 CST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", name=").append(name);
		sb.append(", createTime=").append(createTime);
		sb.append("]");
		return sb.toString();
	}
}